spring:
  application:
    name: karate-flow-api

  mongodb:
    host: localhost
    username: ${MONGO_USER}
    password: ${MONGO_PASSWORD}
    authentication-database: admin
    port: ${MONGO_PORT:27017}
    database: ${MONGO_DB:my_database}

server:
  port: 8081
